Updated the variables and set the default values
UKHO/tfmodule-azure-nsg-flow-logs pull request #3
Opened 2023-07-26 15:02 UTC by GhostShaikh

- Updated the hard coded values.
- Into the variables and also created the variables for the default values.
- Updated Readme

2023-07-28 11:06 UTC, ShaunBresnahan commented
I have tested and it works as intended. We will need to update the spoke example with new version of nsgflowlogs once out of pre-release.

2023-07-31 13:35 UTC, elduddz commented on README.md
> +    default = ""
could we default at 60

if you set default as "" it will pass blank to the varilable and break at the wrong place

2023-07-31 13:35 UTC, elduddz requested changes

2023-07-31 13:35 UTC, elduddz commented on variables.tf
> +variable "intervalminutes" {
Set to default 60

2023-07-31 13:35 UTC, elduddz commented
@ShaunBresnahan @GhostShaikh small change please

2023-08-03 15:09 UTC, GhostShaikh commented on README.md
> +    default = ""
updated the default value to 60

2023-08-03 16:16 UTC, elduddz approved these changes

2023-08-07 07:55 UTC, merged